### ISSUE TITLE
Security alerts triggerred on frontend

### ISSUE THREAD

**Issue by phui** [IUNetSci/BotSlayer-CE#1]
Make sure they are either resolved or safely ignorable. Changes need to be propagated back to the main (enterprise version?) repo.

**Comment by filmenczer** [comment]
Good that Github alerted us of these:
- [ ] Jinja2 ~> 2.10.1
- [ ] lodash.defaultsdeep ~> 4.6.1
- [ ] lodash ~> 4.17.13

**Comment by marcmccarty** [comment]
This should be taken care of on both branches, but can't close here until it's moved here and verified.

**Comment by yangkcatiu** [comment]
Have moved the code here.
