### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by lucmski** [IUNetSci/BotSlayer-CE#12]
Hi guys,

Hope you are all well !

The docker build fails due to https://github.com/IUNetSci/BotSlayer-CE/blob/master/Dockerfile#L16 but there is no docs about it.

Cheers,
L.

**Comment by lucmski** [comment]
sorry but it is still not working as botomoter_lite is missing...

thanks in advance

**Comment by phui** [comment]
I believe that is because of how docker handles relative path in different versions. I have modified the docker file to include only absolute paths.

I have also completed the final test on a fresh new AWS ubuntu machine. The software started running smoothly following the instructions.
