### ISSUE TITLE
JOSS Review: List of dependencies

### ISSUE THREAD

**Issue by nkratzke** [IUNetSci/BotSlayer-CE#14]
Ideally these should be handled with an automated package management solution, this is mainly done in your Docker setting using Python3/NodeJS and the pip/npm package management system.

However, in case of the Postgres database you are relying on the latest Docker image of Postgres SQL according to your Dockerfile.

`FROM library/postgres`

You should add the latest working version here to avoid image build breakdowns of prospective Postgres updates.

Additionally, you could provide a docker image on the Dockerhub for even better user convenience (and simplified installation, the image build took a while).

**Comment by phui** [comment]
@yangkcatiu Can you add the list?

**Comment by yangkcatiu** [comment]
Fix the postgres version to 11.5 in the dockerfile: https://github.com/IUNetSci/BotSlayer-CE/commit/90a51d059a822f830cccd133648baa27165bb2e5

**Comment by nkratzke** [comment]
Perfect. Can be closed.
