### ISSUE TITLE
JOSS Review: Example usage

### ISSUE THREAD

**Issue by nkratzke** [IUNetSci/BotSlayer-CE#15]
According to JOSS guidelines authors should include examples of how to use the software (ideally to solve real-world analysis problems).

The software is not complex to use, however, I missed a small tutorial with a real-world use case. You could add this easily.

What is more, I needed two approaches to figuring out how to insert search terms into the bot detecting engine. A tutorial would be helpful here.

**Comment by yangkcatiu** [comment]
0caaa367478caec334a82de5abfbc3ba13e48864 adds a real world use case and instructions for configure BotSlayer

**Comment by nkratzke** [comment]
Great. Really an improvement. However, I recommend adding a section regarding the Twitter access tokens (you named them APP key which is not perfectly the Twitter terminology as far as I know).

In your screenshot these fields are empty and these fields are hardly mentioned in your explaining text (which might be irritating for novice users). It is likely the most tricky part to generate and figure out these tokens for a novice user. This could simply be done, placing a link to the authoritative [Twitter Developers page](https://developer.twitter.com/en/docs/basics/authentication/guides/access-tokens.html) explaining what these tokens are, how they can be generated and used.

**Comment by marcmccarty** [comment]
We could add it to the readme, but that exact link you sent exists here, in `Help.vue` (the Help page on the frontend):
https://github.com/IUNetSci/BotSlayer-CE/blob/master/frontend/src/views/Help.vue#L17

If you hover over or click the [?] blocks in the Config page, they tell you that more info on twitter keys can be found in the help page. And then there are 3 buttons that lead to different sections of the twitter developer docs, one of which is that page you sent.

**Comment by nkratzke** [comment]
OK, you are right.
