### ISSUE TITLE
JOSS Review: API Documentation

### ISSUE THREAD

**Issue by nkratzke** [IUNetSci/BotSlayer-CE#16]
According to JOSS guidelines the core functionality of the software should be documented to a satisfactory level (e.g., API method documentation)?

I observed the following two points:

- I found no noteworthy API documentation (only some very basic inline comments).
- You architecture figure could be a bit more explicit aligned to your general code organization (backend, middleware, frontend).

**Comment by marcmccarty** [comment]
Commit c782feccc7ee7b9e6acbfbc77d693055f3c40d4d contains more in-depth comments on how the API/middleware functions.

Please let me know if there should be more info in there and/or somewhere else, but I think it's probably sufficient between the new comments and the README.

**Comment by nkratzke** [comment]
Content is fine. However, the API should be documented in a standalone way. A best practice would be to generate the API documentation from the API method comments.

**Comment by marcmccarty** [comment]
@nkratzke How is this?:
https://github.com/IUNetSci/BotSlayer-CE/blob/master/API%20Documentation.md

**Comment by nkratzke** [comment]
Yes great, that heads into the right direction. I wonder whether the API intends to be REST? In that case, the HTTP methods should be stated. However, it seems that all API routes are GET requests? Am I right? So, it is not a REST API (which is a bit sad).

If the API is REST at least the `change_password()`, `config_ini_save()` methods would need POST/PUT/PATCH pendents.

What is more, both methods should have parameters (the properties they change). But there are no parameters described. This is strange, regardless whether the REST style is followed or not.

Furthermore, I am not quite sure why the `jsonify_user_settings()` method is included? It seems to me simply a helper method for `config_read_ep()` but is not exposed to the API itself? If that is correct it is a private helper method and should not be exposed to the API documentation (it is not callable or is it?).

**Comment by marcmccarty** [comment]
The API is not technically REST. It is not intended for independent consumption, but rather just to be used as an interface between the frontend and the middleware/backend.\
It wasn't intended to be used independently, which is why we didn't design it to conform to REST standards.

I added the parameters that are passed.

I removed the helper function.

**Comment by yangkcatiu** [comment]
d1d04cef53f22d0d8a00681bc8dae80610f2ce7f updates the system architecture illustration.

**Comment by nkratzke** [comment]
Except some typos in the API documentation, I think your work improved the documentation. Thank you very much. I will close this issue. However, a proof-reading of the API documentation should be done.
