### ISSUE TITLE
JOSS Review: Community guidelines

### ISSUE THREAD

**Issue by nkratzke** [IUNetSci/BotSlayer-CE#18]
According to JOSS guidelines, community guidelines should be provided. These should cover guidelines for third parties wishing to 

1. contribute to the software,
2. report issues or problems with the software,
3. seek support.

**Comment by yangkcatiu** [comment]
284a2d9fe45966cc7638aed48df3d4f5cf456249 community guidelines added.

**Comment by nkratzke** [comment]
Well done. Issue can be closed according to my evaluation.
