### ISSUE TITLE
Clarify bot detection limitations

### ISSUE THREAD

**Issue by filmenczer** [IUNetSci/BotSlayer-CE#2]
We should clearly communicate that: 
> The "CE" version of BotSlayer is not meant for real research, as it uses simple heuristics to calculate bot scores. We strongly recommend the "Pro" version of BotSlayer, which has proprietary BotometerLite software and many other improvements. It is available for free, but will share data with Indiana University for research purposes. 

These differences should be articulated in multiple places:
- [x] The BotSlayer tool page on the OSoMe website
- [x] The README of this repo
- [x] Comments in the code
- [x] The BotSlayer CE front-end
  - [x] RED warning to Botness column
  - [x] permanent, closable banner warning
  - [x] update the About page
- [x] The paper about BotSlayer CE in open source journal

**Comment by yangkcatiu** [comment]
Have updated all the docs regarding the bot detection.
