### ISSUE TITLE
JOSS Review (@mkearney): Target Audience

### ISSUE THREAD

**Issue by mkearney** [IUNetSci/BotSlayer-CE#21]
* [x] Given the real-time and interactive nature of *BotSlayer* and its relationship to public-opinion/affairs, **I think the intended audience (currently phrased as *'researchers'* or *'academic researchers'* in `paper.md` and `README.md`) should also include *'journalists'*–who not only have an interest in this topic but also have an [entire organization dedicated to computer-assisted reporting](https://www.ire.org/nicar)**.

**Comment by marcmccarty** [comment]
OSoMe's BotSlayer page and the About page of the application mention that journalists, corporations, and political candidates could be interested in using BotSlayer.

I agree that we can and should include it in the places you listed, though.

Our organization's page (https://osome.iuni.iu.edu/tools/botslayer/) 
and the "About" page of the app (`About.vue`): https://github.com/IUNetSci/BotSlayer-CE/blob/master/frontend/src/views/About.vue

**Comment by yangkcatiu** [comment]
55a1188ef0c21d17d6d14c3c2076b9da75232920 and 0f63e79b492c963c0aef1a81db26766f3a7e2b94 should address this issue.

**Comment by filmenczer** [comment]
Can this issue be closed?
