### ISSUE TITLE
JOSS Review (@mkearney): Export user id_str

### ISSUE THREAD

**Issue by mkearney** [IUNetSci/BotSlayer-CE#22]
* [x] The tool exports `screen_name` as the user/account identifier, but screen names can be changed and are thus not stable identifiers. **The exported output should therefore include the user `id_str` value returned by Twitter's stream API**.

**Comment by phui** [comment]
Relevant discussion on-going at #23.

**Comment by filmenczer** [comment]
We settled on a compromise solution that should facilitate data access while minimizing risks. See discussion of #23 

This should address this issue.

**Comment by filmenczer** [comment]
Can this issue be closed?
