### ISSUE TITLE
How do I do a password reset - and don't know old PW? Where do I find current PW? 

### ISSUE THREAD

**Issue by joemcl** [IUNetSci/BotSlayer-CE#28]
So, I have the 'non-community' image running in docker locally. I created a password under Config, using LastPass. I did not save it :( . To log in, now I need to create another, using Change Password, which I *will* be sure to save :). Where can I find the old, saved password?

**Comment by joemcl** [comment]
Maybe easier/ better to just uninstall and reinstall?

**Comment by joemcl** [comment]
So I ran `sudo docker rmi -f bev` and removed the old image. Then re-loaded the image. But, the config settings with the old password are still there, of course - the new image has the same name as the old.

**Comment by phui** [comment]
To change the password via UI, one has to supply the old password. This is to prevent an unauthorized user from resetting the password.

If the system admin has forgotten the password, the only ways currently are:

1. access the database and modify the `config` table directly
2. remove both image and **volumes** and install `BotSlayer-CE` again

**Comment by phui** [comment]
Feel free to reopen the issue if you have questions.

**Comment by joemcl** [comment]
OK thanks. Makes sense. I assume you mean there is a config table in the postgres database. So when I run this per the readme - 
`psql -U bev -h localhost -p 5432 bev`
I get this - 
`Password for user bev: 
psql: FATAL:  password authentication failed for user "bev"
FATAL:  password authentication failed for user "bev"`

**Comment by joemcl** [comment]
Though I'm running the 'pro' version now, and perhaps the db settings are different?

**Comment by phui** [comment]
The command

    psql -U bev -h localhost -p 5432 bev

will prompt for password input. The password is `bev`. This is part of the [Data Export](Data Export) section of the documentation.

You are correct that the db settings differ a bit between the `pro` and the `CE` versions. At the moment this way to access the database should work. If there is an update we will update the `CE` version, or provide separate instructions.

**Comment by joemcl** [comment]
OK thanks, I realized it's a postgres issue on my machine.
