### ISSUE TITLE
docker build --tag=bsce requires an argument

### ISSUE THREAD

**Issue by joemcl** [IUNetSci/BotSlayer-CE#29]
Per the readme.md, I'm doing this:
"Enter the repo directory, and build the docker image by [running]" `docker build --tag=bsce .`
and I get this response:
`"docker build" requires exactly 1 argument.
See 'docker build --help'.
Usage:  docker build [OPTIONS] PATH | URL | -
Build an image from a Dockerfile`

**Comment by joemcl** [comment]
OK so I did this: 'cd' to go to 'home', then `sudo docker build /home/joe/BotSlayer-CE --tag=bsce` . That ran the build.

**Comment by phui** [comment]
@joemcl I believe you have missed the dot at the end of the command, which represent the current working directory. The command requires a path where the `Dockerfile` is located.

**Comment by joemcl** [comment]
aha. I thought the dot was a period :) . So perhaps enclose the command in quotes, including the dot.
