### ISSUE TITLE
postgres database "bev" does not exist

### ISSUE THREAD

**Issue by joemcl** [IUNetSci/BotSlayer-CE#30]
When I run 
`psql -U bev -h localhost -p 5432 bev`
and enter PW `bev`, I get this:
` psql: FATAL:  password authentication failed for user "bev"
FATAL:  password authentication failed for user "bev"` .
When I run
`sudo psql -U bev -h localhost -p 5432 bev`
and enter PW `bev`, I get the same as above.
When I run
`sudo psql -U postgres -h localhost -p 5432 bev`
and log in with correct PW, I get this:
`psql: FATAL:  database "bev" does not exist`.
When I run
`sudo psql -U postgres -h localhost -p 5432` 
and log in with correct PW, I get this:
`psql (11.5 (Ubuntu 11.5-0ubuntu0.19.04.1), server 9.6.12)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.`
and I can enter `\l` at `postgres=#` and see my existing databases.

**Comment by phui** [comment]
I believe you are using the docker image to launch BotSlayer in your own machine (perhaps a work desktop or private server).

In this case, your machine may have a running instance of PostgreSQL database listening at port 5432 already when BotSlayer launches. The host machine will keep listening to its running PostgreSQL database instead of binding the `docker_container:5432` to `localhost:5432`.

You really shouldn't see your existing databases, because the binded PostgreSQL database should be the one running inside the docker container, which only has `bev` database.

A solution is to bind the SQL port to 5433 instead and connect to port 5433 locally.

    docker run -dit -p 5433:5432 -p 5000:5000 -p 9001:9001 -v pgdata:/var/lib/postgresql/data bsce
    psql -U bev -h localhost -p 5433

And then enter the password.

In our testing environment, conflict of port mapping will stop the launching and display an informative message saying the port is already occupied. There may be different behaviors in different OS...

**Comment by joemcl** [comment]
Yes, I'm running docker on my laptop - `Docker version 19.03.2, build 6a30dfca03`. Because I can do that and test BotSlayer out for free, then try it on AWS if I want to spend some money :) .
 
OS info is: `No LSB modules are available. Distributor ID: Ubuntu , Description: Pop!_OS 19.04, Release: 19.04, Codename: disco`

Postgres version is: `psql (PostgreSQL) 11.5 (Ubuntu 11.5-0ubuntu0.19.04.1)` and I'm using pgAdmin 3 and pgAdmin 4 for other stuff - `pgAdmin III 1.22.2` 

So I'll try `bind[ing] the SQL port to 5433 instead and connect to port 5433 locally` per above.

Thanks!

**Comment by joemcl** [comment]
and since I'm apparently running Postgres on both 5432 and 5433 already for pgAdmin stuff, I'll use 5434 instead per above, and look around for how I find all of my already mapped ports :) . Thanks again.

**Comment by joemcl** [comment]
Cool, so I did `sudo -i`, ran `netstat -nptl` as root, and I see all listening ports. Apparently I have 5432 through 5435 bound to Postgres already - so will try 5436. Hi @filmenczer I'd prefer to close my own issue, thanks! Once I get up and running on say 5436 :) . Also, would be worth specifying in the Docker instructions that if folks are running it on their own local machine rather than an external server, they should look at this Issue.

**Comment by joemcl** [comment]
So, I'm first stopping, removing and pruning my old, existing docker container - 
`sudo docker stop 49960797a719` then `sudo docker container rm 49960797a719` then `sudo docker container prune`. 
Then, removing and pruning the old, existing docker volume  - `sudo docker volume rm pgdata` and `sudo docker volume prune` .

**Comment by filmenczer** [comment]
Sorry I thought the issue had been addressed. @phui has opened a separate issue #31 about documenting the possible port conflict.

**Comment by joemcl** [comment]
Now, since I'm running the 'pro' version, doing this to re-install, from `/home/joe/BotSlayer-CE` :
`sudo docker build --tag=bev .
sudo docker volume create pgdata
sudo docker volume create rpdata
sudo docker run -dit -p 5436:5432 -p 5000:5000 -p 9001:9001 -v pgdata:/var/lib/postgresql/data bev
psql -U bev -h localhost -p 5436`

**Comment by joemcl** [comment]
yay, that worked! Though I will walk back through these steps to use the 'pro' version instead. Thanks so much @phui and @filmenczer for developing BotSlayer. Closing now.

**Comment by joemcl** [comment]
> Sorry I thought the issue had been addressed. @phui has opened a separate issue #31 about documenting the possible port conflict.
@filmenczer cool, closed now after my public 'rubber ducking' :)
