### ISSUE TITLE
Where do we submit bug reports for the 'pro' version, and python error

### ISSUE THREAD

**Issue by joemcl** [IUNetSci/BotSlayer-CE#32]
Not sure where to submit bug reports for the 'pro' edition/version, or even if this is necessarily an issue only with the 'pro' version. But I don't recall seeing this warning when running the community edition - 
`/usr/local/lib/python3.5/dist-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.20.2 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.`

**Comment by filmenczer** [comment]
I am not sure if this particular issue is about BotSlayer-CE (in which case submitting issues here is the right thing to do) or about the specific classified in the 'pro' version, in which case you can contact us via email. @yangkcatiu will be able to answer this.

**Comment by joemcl** [comment]
thanks @filmenczer !

**Comment by phui** [comment]
We are aware of that specific warning. For now it is harmless. We will have a fix for it in the next release of the pro version.

**Comment by joemcl** [comment]
thanks @phui .
