### ISSUE TITLE
Can we use Boolean operators with search terms? 

### ISSUE THREAD

**Issue by joemcl** [IUNetSci/BotSlayer-CE#34]
Can we use Boolean operators - AND, OR, NOT, (), “” - in queries and/or filters?

**Comment by phui** [comment]
Our query input is supported by Twitter's streaming API. Therefore we can only provide what Twitter provides.

Your query input is fed into the `track` parameter in the API. Twitter allows for AND and OR operations.

To know more about the track parameter and how it works, you can read on https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/basic-stream-parameters

**Comment by joemcl** [comment]
Thanks @phui so in the BotSlayer UI then, I can use AND and OR operators?

**Comment by joemcl** [comment]
So OK seems 'yes' is the answer

**Comment by filmenczer** [comment]
I do not think so. Please refer to the Twitter documentation linked by @phui.
