### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by MattMacs** [IUNetSci/BotSlayer-CE#40]
The docker build fails at https://github.com/IUNetSci/BotSlayer-CE/blob/master/Dockerfile#L26 with:

```
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "^^2.1.1": Tags may not have any characters that encodeURIComponent encodes.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-13T19_30_38_107Z-debug.log
```

**Comment by MattMacs** [comment]
found the problem, typo in https://github.com/IUNetSci/BotSlayer-CE/blob/master/frontend/package-lock.json#L3002, pull request opened

**Comment by marcmccarty** [comment]
#41 by @MattMacs fixes this.

**Comment by phui** [comment]
Our frontend developer @marcmccarty has looked at your PR and merged. Thank you very much for bringing this up and contributing!
